services:
  emby302:
    image: emby302/emby302:latest
    restart: unless-stopped
    ports:
      - "8095:8095"
      - "8098:8098"
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
